In [16]:
from __future__ import print_function
import torch
import numpy as np

In [4]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
x = torch.zeros(5, 3, dtype=torch.long)
y = torch.rand(5, 3)

print(x + y)
print(torch.add(x, y))

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

y.add_(x)
print(y)

tensor([[0.2532, 0.5823, 0.0417],
        [0.2263, 0.8171, 0.9080],
        [0.1784, 0.1051, 0.9090],
        [0.8247, 0.9915, 0.8670],
        [0.3713, 0.7314, 0.6082]])
tensor([[0.2532, 0.5823, 0.0417],
        [0.2263, 0.8171, 0.9080],
        [0.1784, 0.1051, 0.9090],
        [0.8247, 0.9915, 0.8670],
        [0.3713, 0.7314, 0.6082]])
tensor([[0.2532, 0.5823, 0.0417],
        [0.2263, 0.8171, 0.9080],
        [0.1784, 0.1051, 0.9090],
        [0.8247, 0.9915, 0.8670],
        [0.3713, 0.7314, 0.6082]])
tensor([[0.2532, 0.5823, 0.0417],
        [0.2263, 0.8171, 0.9080],
        [0.1784, 0.1051, 0.9090],
        [0.8247, 0.9915, 0.8670],
        [0.3713, 0.7314, 0.6082]])


In [12]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) 

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
b = y.numpy()

print(y)
print(b)

tensor([ 0.4422,  0.9213, -0.7187,  2.3405,  0.2988,  0.3618, -1.9770,  0.9796,
        -0.3123, -0.6932,  0.7265,  0.0392,  0.5313,  1.0917, -0.5391,  0.8513])
[ 0.44216752  0.9212777  -0.7186719   2.3404586   0.2987877   0.3617993
 -1.9770199   0.9795505  -0.3123176  -0.69316894  0.72650135  0.03922523
  0.53130275  1.0916877  -0.5390634   0.8513322 ]


In [17]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [75]:
x = torch.ones(2, 2, requires_grad=True) #.requires_grad 속성을 True 로 설정하면, 그 tensor에서 이뤄진 모든 연산들을 추적(track)하기 시작
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [57]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [58]:
z = y * y * 3
print(z)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)


In [59]:
z.grad_fn

out = z.mean()

out

tensor(27., grad_fn=<MeanBackward0>)

In [60]:
out.backward(torch.tensor(3)) #backward를 호출하면 모든 그래디언트를 자동으로 계산할 수 있음

# = out.backward(torch.tensor(1))

In [61]:
x.grad #x로 미분

tensor([[13.5000, 13.5000],
        [13.5000, 13.5000]])

In [65]:
x = torch.ones(2, 2, requires_grad=True)

y = x + 2

z = y * y * 3

out = z.mean()

out.backward()

x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [83]:
x = torch.ones(2, 2, requires_grad=True)

y = x + 2

z = y * y * 3

out = z.mean()

print(out)

out.backward(torch.tensor(3))

x.grad

tensor(27., grad_fn=<MeanBackward0>)


tensor([[13.5000, 13.5000],
        [13.5000, 13.5000]])

In [95]:
x = torch.randn(2, 2, requires_grad=True)
y = x + 2
z = y * y * 3

t = torch.tensor([0.1, 1, 0.01, 10]) 

z = z.reshape(4)

print(z)

z.backward(t)  #z가 1,4 쉐입이라 1,4쉐입의 텐서가 들어가야함~!

x.grad

tensor([33.9297,  5.3782,  2.7715,  6.2372], grad_fn=<ViewBackward>)


tensor([[2.0178e+00, 8.0336e+00],
        [5.7670e-02, 8.6514e+01]])